import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className }>
        <div className="max-w-[1600px] m-auto">
        <header className="bg-black text-white">
          <div className=" py-2 flex gap-8 justify-end px-40">
            <a className="cursor-pointer hover:text-amber-800" href="/signIn">Sign in / Guest</a>
            <a className="cursor-pointer hover:text-amber-800" href="/createAccaunt">Create Account</a>
          </div>
        </header>
        <nav className="bg-gray-300">
          <div className="py-2 px-40 flex justify-between items-center">
            <span className="text-3xl font-bold py-2 px-4 rounded-lg bg-blue-600 cursor-pointer hover:bg-blue-800">
              C

            </span>
            <ul className="flex gap-4 ">
              <li>
                <a className="py-2 px-4 hover:bg-black hover:text-white rounded-lg" href="/">
                  Home
                </a>
              </li>
              <li>
                <a className="py-2 px-4 hover:bg-black hover:text-white rounded-lg" href="/about">
                  About
                </a>
              </li>
              <li>
                <a className="py-2 px-4 hover:bg-black hover:text-white rounded-lg" href="/product">
                  Product
                </a>
              </li>
              <li>
                <a className="py-2 px-4 hover:bg-black hover:text-white rounded-lg" href="/cart">
                  Cart
                </a>
              </li>
            </ul>
            <div className="flex gap-4 items-center">
                <svg
                  stroke="currentColor"
                  fill="currentColor"
                  stroke-width="0"
                  viewBox="0 0 16 16"
                  class="cursor-pointer"
                  height="1em"
                  width="1em"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
                </svg>
              <div class="indicator">
                <svg
                  stroke="currentColor"
                  fill="currentColor"
                  stroke-width="0"
                  viewBox="0 0 16 16"
                  className="cursor-pointer"
                  height="1em"
                  width="1em"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path>
                </svg>
              </div>
            </div>
          </div>
        </nav>
        {children}
        </div>
      </body>
    </html>
  );
}
